//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDatHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoAnEntities : DbContext
    {
        public DoAnEntities()
            : base("name=DoAnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HDDatHang> HDDatHangs { get; set; }
        public virtual DbSet<Khach> Khaches { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<MonAn> MonAns { get; set; }
        public virtual DbSet<MonAn_HDDatHang> MonAn_HDDatHang { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NuocUong> NuocUongs { get; set; }
        public virtual DbSet<NuocUong_HDDatHang> NuocUong_HDDatHang { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
