//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDatHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuocUong_HDDatHang
    {
        public int MaNuocUong { get; set; }
        public int MaHDDatHang { get; set; }
        public decimal Gia { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HDDatHang HDDatHang { get; set; }
        public virtual NuocUong NuocUong { get; set; }
    }
}
