//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDatHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuocUong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NuocUong()
        {
            this.NuocUong_HDDatHang = new HashSet<NuocUong_HDDatHang>();
        }
    
        public int MaNuocUong { get; set; }
        public decimal Gia { get; set; }
        public string TenNuocUong { get; set; }
        public int SoLuongCon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NuocUong_HDDatHang> NuocUong_HDDatHang { get; set; }
    }
}
